name: python pipeline

on: push

jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py  
  build:
    needs: [test]
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifacts@v2
        with:
          name: hello
          path: .
